server:
  port: 5151
eureka:
  instance:
    hostname: 34.227.104.40
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/